---

- hosts: localhost
  become: true
  vars_files:
    - group_vars/all.yml

  tasks:

  - name: Copy CA certificate to elasticsearch directory
    copy:
      src: /usr/share/elasticsearch/ca/ca.crt
      dest: /etc/logstash/ca.crt
      owner: root
      group: root
      mode: 0644

  - name: Change Logstash's minimum memory usage to 512MB
    lineinfile:
      path: /etc/logstash/jvm.options
      regexp: "^-Xms"
      line: "-Xms512m"
      state: present

  - name: Change Logstash's maximum memory usage to 512MB
    lineinfile:
      path: /etc/logstash/jvm.options
      regexp: "^-Xmx"
      line: "-Xmx512m"
      state: present

  - name: Add the Logstash configuration which activates monitoring
    template: src=templates/logstash/logstash.yml dest=/etc/logstash/logstash.yml

  - name: Add the Logstash input configuration for Beats
    template: src=templates/logstash/beats-input.conf dest=/etc/logstash/conf.d/00-beats-input.conf

  - name: Add the Logstash input configuration for Redis
    template: src=templates/logstash/redis-input.conf dest=/etc/logstash/conf.d/01-redis-input.conf

#  - name: Add the Logstash filter configuration for Syslog
#    template: src=templates/logstash/syslog-filter.conf dest=/etc/logstash/conf.d/10-syslog-filter.conf

  - name: Add an empty Logstash filter configuration
    template: src=templates/logstash/empty-filter.conf dest=/etc/logstash/conf.d/11-empty-filter.conf

  - name: Add the Logstash filter configuration for YUM.log
    template: src=templates/logstash/yum-filter.conf dest=/etc/logstash/conf.d/12-yum-filter.conf

  - name: Add the Logstash output configuration to Elasticsearch
    template: src=templates/logstash/elasticsearch-output.conf dest=/etc/logstash/conf.d/20-elasticsearch-output.conf

  - name: Change Elasticsearch output user password
    lineinfile:
      path: /etc/logstash/conf.d/20-elasticsearch-output.conf
      regexp: "password => x-pack-test-password"
      line: "password => {{ logstash_internal_password }}"
      state: present

  - name: Add logstash system user for monitoring
    lineinfile:
      path: /etc/logstash/logstash.yml
      regexp: "^xpack.monitoring.elasticsearch.username:"
      line: "xpack.monitoring.elasticsearch.username: 'logstash_system'"
      state: present

  - name: Add logstash system user for monitoring
    lineinfile:
      path: /etc/logstash/logstash.yml
      regexp: "^xpack.monitoring.elasticsearch.password:"
      line: "xpack.monitoring.elasticsearch.password: '{{ logstash_system_user_password }}'"
      state: present

  - name: Add CA cert for monitoring
    lineinfile:
      path: /etc/logstash/logstash.yml
      regexp: "^xpack.monitoring.elasticsearch.ssl.certificate_authority:"
      line: "xpack.monitoring.elasticsearch.ssl.certificate_authority: /etc/logstash/ca.crt"
      state: present

  - name: Create the pattern directory
    file: path=/opt/logstash/patterns/ state=directory recurse=yes

  - name: Add the nginx pattern, so we can use it for workshops later on
    template: src=templates/logstash/nginx-pattern dest=/opt/logstash/patterns/nginx

  - name: Start Logstash
    service: name=logstash state=restarted
