---

- hosts: localhost
  become: true
  vars_files:
    - group_vars/all.yml

  tasks:

  - name: Change the Heartbeat configuration
    template: src=templates/heartbeat.yml dest=/etc/heartbeat/heartbeat.yml

  - name: Apply elastic user password to configuration
    lineinfile:
      path: /etc/heartbeat/heartbeat.yml
      regexp: "^output.elasticsearch.password:"
      line:  "output.elasticsearch.password: '{{ elastic_user_password }}'"
      state: present

  - name: Apply kibana user password to configuration
    lineinfile:
      path: /etc/heartbeat/heartbeat.yml
      regexp: "^setup.kibana.password:"
      line:  "setup.kibana.password: '{{ elastic_user_password }}'"
      state: present

  - name: Restart Heartbeat
    service: name=heartbeat-elastic state=restarted

  - name: Wait if Heartbeat is actually running
    pause: minutes=1

  - name: Get the state of all services and check the status of Heartbeat
    service_facts: ~
    failed_when: ansible_facts.services["heartbeat-elastic"].state != "running"

  - name: Check if we actually have documents in Heartbeat's index
    uri:
      url: https://127.0.0.1:9200/heartbeat-*/_count
      user: elastic
      password: "{{ elastic_user_password }}"
      method: GET
      status_code:
        - 200
      return_content: yes
      validate_certs: no
    register: response
    failed_when: 'response.json["count"]|int == 0'
