#==========================  Modules configuration ============================
filebeat.modules:

#------------------------------- System Module -------------------------------
- module: system
#------------------------------- Auditd Module -------------------------------
- module: auditd
#------------------------------ logstash Module ------------------------------
- module: logstash
#------------------------------- mongodb Module ------------------------------
- module: mongodb
#-------------------------------- Nginx Module -------------------------------
- module: nginx
#-------------------------------- osquery Module -----------------------------
- module: osquery
#-------------------------------- Redis Module -------------------------------
- module: redis


#=========================== Filebeat inputs =============================

# List of inputs to fetch data.
filebeat.inputs:
- type: log
  enabled: true
  paths:
    - /var/log/kibana/kibana.log
  json.message_key: log
#  fields:
#    type: kibana

# filebeat.autodiscover:
#   # List of enabled autodiscover providers
#   providers:
#     - type: docker
#       templates:
#         - condition:
#             equals.docker.container.image: busybox
#           config:
#             - type: log
#               paths:
#                 - /var/lib/docker/containers/${data.docker.container.id}/*.log

processors:
- add_docker_metadata: ~
- add_host_metadata: ~

#================================ Outputs ======================================

#-------------------------- Elasticsearch output -------------------------------
output.elasticsearch:
  enabled: true
  hosts: ["127.0.0.1:9200"]
  protocol: "https"
  ssl.certificate_authorities: ["/usr/share/elasticsearch/ca/ca.crt"]
  ssl.certificate: "/usr/share/elasticsearch/instance/instance.crt"
  ssl.key: "/usr/share/elasticsearch/instance/instance.key"
  username: "elastic"

#----------------------------- Logstash output ---------------------------------
output.logstash:
  enabled: false
  hosts: ["localhost:5044"]

#============================== Kibana =====================================

setup.kibana:
  host: "127.0.0.1:5601"
  protocol: "https"
  username: "elastic"
  ssl.enabled: true
  ssl.certificate_authorities: ["/usr/share/elasticsearch/ca/ca.crt"]
  ssl.certificate: "/usr/share/elasticsearch/instance/instance.crt"
  ssl.key: "/usr/share/elasticsearch/instance/instance.key"
  dashboards:
    enabled: true
    always_kibana: true #Only talk to Kibana, which is important for the retry
    retry.enabled: true #Retry in case Kibana is not up yet

#============================== Xpack Monitoring =====================================

xpack.monitoring.enabled: true

