############################# Heartbeat ######################################

# Configure monitors
heartbeat.monitors:
- type: http
  schedule: '@every 10s'
  urls: ["http://localhost:80"]
  check.response:
    status: 200

#================================ Processors ===================================

processors:
- add_docker_metadata: ~
- add_host_metadata: ~

#================================ Outputs ======================================

#-------------------------- Elasticsearch output -------------------------------
output.elasticsearch:
  enabled: true
  hosts: ["127.0.0.1:9200"]
  protocol: "https"
  ssl.certificate_authorities: ["/usr/share/elasticsearch/ca/ca.crt"]
  ssl.certificate: "/usr/share/elasticsearch/instance/instance.crt"
  ssl.key: "/usr/share/elasticsearch/instance/instance.key"
  username: "elastic"

#----------------------------- Logstash output ---------------------------------
output.logstash:
  enabled: false
  hosts: ["localhost:5044"]

#============================== Kibana =====================================

ssetup.kibana:
  host: "127.0.0.1:5601"
  protocol: "https"
  username: "elastic"
  ssl.enabled: true
  ssl.certificate_authorities: ["/usr/share/elasticsearch/ca/ca.crt"]
  ssl.certificate: "/usr/share/elasticsearch/instance/instance.crt"
  ssl.key: "/usr/share/elasticsearch/instance/instance.key"
  dashboards:
    enabled: true
    always_kibana: true #Only talk to Kibana, which is important for the retry
    retry.enabled: true #Retry in case Kibana is not up yet

#============================== Xpack Monitoring =====================================

xpack.monitoring.enabled: true

